# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 22:25
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('limit_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'open', 'Open'), (b'moving', 'Moving'), (b'close', 'Cerrar')], db_index=True, default=b'open', max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.CharField(max_length=255, verbose_name='Preferences')),
                ('give_gift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Inscription')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='base.Group', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'ordering': ('first_name',),
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='base.User', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_created', to='base.User', verbose_name='Creator'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set([('user', 'group')]),
        ),
    ]
